### ISSUE TITLE
Crashes on starting an application using socket.io-store-memcached

### ISSUE THREAD

**Issue by todoa2c** [nowelium/socket.io-store-memcached#2]
My application crashes on starting using socket.io-store-memcached.

My environment is:
Node.js v0.10.17 on Linux/Windows
socket.io v0.9.16
socket.io-store-memcached v0.1.2

This is my result using your examples/chat.js on that environment:

```
$ node chat.js
   info  - socket.io started

crypto.js:188
  this._binding = new binding.Hash(algorithm);
                  ^
Error: Digest method not supported
    at new Hash (crypto.js:188:19)
    at Object.Hash (crypto.js:187:12)
    at HashRing.hash (js/node_modules/socket.io-store-memcached/node_modules/memcached/node_modules/hashring/index.js:199:17)
    at HashRing.digest (js/node_modules/socket.io-store-memcached/node_modules/memcached/node_modules/hashring/index.js:210:19)
    at each (js/node_modules/socket.io-store-memcached/node_modules/memcached/node_modules/hashring/index.js:112:16)
    at Array.forEach (native)
    at HashRing.generate [as continuum] (js/node_modules/socket.io-store-memcached/node_modules/memcached/node_modules/hashring/index.js:100:11)
    at new HashRing (js/node_modules/socket.io-store-memcached/node_modules/memcached/node_modules/hashring/index.js:77:8)
    at EventEmitter.Client (js/node_modules/socket.io-store-memcached/node_modules/memcached/lib/memcached.js:49:19)
    at new Memcached (js/node_modules/socket.io-store-memcached/lib/index.js:60:20)
```

**Comment by idris** [comment]
Can you please publish this new version to npm?

**Comment by nowelium** [comment]
Sorry.. It was published just now
